runtime: python39

handlers:
- url: /.*
  script: auto
  secure: always

env_variables:
  LINE_CHANNEL_SECRET: fa28c66980cf43dd8b1e41630b2f8fd1
  LINE_CHANNEL_ACCESS_TOKEN: plMcM04uPLPHEsBYPqZZtFHj0pM9I19dOVByC5fp7FZf4gFTW83BZVWYBcTW/g/ENqoWfTrIUx6tLCyAVLRuGh4At1PXF2GZPqhTvswClAZCphOFNRgDyAvobPNymbm4D04ZsOAxaq8d9wNT6ojOxwdB04t89/1O/w1cDnyilFU=
  GOOGLE_CLOUD_PROJECT: ultimate-triode-362907
  CLOUD_STORAGE_BUCKET: linebot_stock_helper

service: linebot-cloud
instance_class: F1

beta_settings:
  cloud_sql_instances: ultimate-triode-362907:asia-east1:linebot_stock_helper

runtime_config:
  python_version: 3.9

inbound_services:
- warmup

network:
  session_affinity: true

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

automatic_scaling:
  min_instances: 1
  max_instances: 3
  target_cpu_utilization: 0.6
  min_pending_latency: 30ms
  max_pending_latency: automatic
